import type { Metadata } from "next";
import { Geist, Geist_Mono, Kalam, Patrick_Hand, Patrick_Hand_SC, Sora, Saira } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "./components/Home/Navbar/ResponsiveNav";
import Footer from "./components/Home/Footer/Footer";
import ScrollToTop from "./components/Helper/ScrollToTop";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sora = Sora({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ['latin']
})

const patrick = Patrick_Hand({
  weight: ["400"]
})

const kalam = Kalam({
  weight: ["300", "400", "700"],
})

const saira = Saira({
  weight:["200", "300"]
})

export const metadata: Metadata = {
  title: "Cesar Banchio Developer Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={saira.className}
      >
        <ResponsiveNav />
        {children}
         <Footer />
         <ScrollToTop />
      </body>
    </html>
  );
}
